name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: thesis
          root_file: master.tex     
      - uses: actions/upload-artifact@v2
        with:
          name: master.pdf
          path: thesis/master.pdf
